### ISSUE TITLE
Hello, I tried to run the program, but I get an error. Please help me!

### ISSUE THREAD

**Issue by dapsi0404** [chaudoe/Newtures#1]
C:\Users\Hamstr\AppData\Local\Programs\Python\Python38\Newtures-master>python clock.py
  File "clock.py", line 14
    <<<<<<< HEAD
    ^
SyntaxError: invalid syntax

**Comment by dapsi0404** [comment]
020-09-18 19:15:00.019043
Job "timed_job (trigger: cron[day_of_week='mon-sun', hour='0-23', minute='0-59/15'], next run at: 2020-09-18 19:30:00 MSK)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Hamstr\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\Hamstr\AppData\Local\Programs\Python\Python38\Newtures-f8f66baf7f3b07f98f377f4a0094b16104eda4f1\clock.py", line 28, in timed_job
    con()
  File "C:\Users\Hamstr\AppData\Local\Programs\Python\Python38\Newtures-f8f66baf7f3b07f98f377f4a0094b16104eda4f1\clock.py", line 15, in con
    t1 = threading.Thread(target=strategy.run(**trx))
  File "C:\Users\Hamstr\AppData\Local\Programs\Python\Python38\Newtures-f8f66baf7f3b07f98f377f4a0094b16104eda4f1\strategy.py", line 208, in run
    step1 = start(symbol, quote, base, step_size, leverage, interval, roundQuant, position)
  File "C:\Users\Hamstr\AppData\Local\Programs\Python\Python38\Newtures-f8f66baf7f3b07f98f377f4a0094b16104eda4f1\strategy.py", line 28, in __init__
    self.baseBalance = float(Binance.client.futures_get_all_orders(symbol=self.symbol)[-1]['origQty'])
IndexError: list index out of range

**Comment by ch-m-n** [comment]
> 020-09-18 19:15:00.019043
> Job "timed_job (trigger: cron[day_of_week='mon-sun', hour='0-23', minute='0-59/15'], next run at: 2020-09-18 19:30:00 MSK)" raised an exception
> Traceback (most recent call last):
> File "C:\Users\Hamstr\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
> retval = job.func(*job.args, **job.kwargs)
> File "C:\Users\Hamstr\AppData\Local\Programs\Python\Python38\Newtures-f8f66baf7f3b07f98f377f4a0094b16104eda4f1\clock.py", line 28, in timed_job
> con()
> File "C:\Users\Hamstr\AppData\Local\Programs\Python\Python38\Newtures-f8f66baf7f3b07f98f377f4a0094b16104eda4f1\clock.py", line 15, in con
> t1 = threading.Thread(target=strategy.run(**trx))
> File "C:\Users\Hamstr\AppData\Local\Programs\Python\Python38\Newtures-f8f66baf7f3b07f98f377f4a0094b16104eda4f1\strategy.py", line 208, in run
> step1 = start(symbol, quote, base, step_size, leverage, interval, roundQuant, position)
> File "C:\Users\Hamstr\AppData\Local\Programs\Python\Python38\Newtures-f8f66baf7f3b07f98f377f4a0094b16104eda4f1\strategy.py", line 28, in **init**
> self.baseBalance = float(Binance.client.futures_get_all_orders(symbol=self.symbol)[-1]['origQty'])
> IndexError: list index out of range

Hi, sorry for messy code, this is just a draft for my bot so I didn't expect someone really notice my repository. My bad 😕. If you're still interested in this one, I just rewrite this repository and matching it with the bot I currently use, hope that help.
